/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.DirectoryCatalogue;
import de.samply.bbmri.negotiator.jooq.tables.records.DirectoryCatalogueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Table to store directorys
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryCatalogueDao extends DAOImpl<DirectoryCatalogueRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue, Integer> {

	/**
	 * Create a new DirectoryCatalogueDao without any configuration
	 */
	public DirectoryCatalogueDao() {
		super(DirectoryCatalogue.DIRECTORY_CATALOGUE, de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue.class);
	}

	/**
	 * Create a new DirectoryCatalogueDao with an attached configuration
	 */
	public DirectoryCatalogueDao(Configuration configuration) {
		super(DirectoryCatalogue.DIRECTORY_CATALOGUE, de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchById(Integer... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue fetchOneById(Integer value) {
		return fetchOne(DirectoryCatalogue.DIRECTORY_CATALOGUE.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByName(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.NAME, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByUrl(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.URL, values);
	}

	/**
	 * Fetch records that have <code>rest_url IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByRestUrl(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.REST_URL, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByUsername(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.USERNAME, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByPassword(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>api_username IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByApiUsername(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.API_USERNAME, values);
	}

	/**
	 * Fetch records that have <code>api_password IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByApiPassword(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.API_PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>resource_biobanks IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByResourceBiobanks(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.RESOURCE_BIOBANKS, values);
	}

	/**
	 * Fetch records that have <code>resource_collections IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByResourceCollections(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.RESOURCE_COLLECTIONS, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchByDescription(String... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>sync_active IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.DirectoryCatalogue> fetchBySyncActive(Boolean... values) {
		return fetch(DirectoryCatalogue.DIRECTORY_CATALOGUE.SYNC_ACTIVE, values);
	}
}
